name: photoline_example
description: Photoline plugin.
version: 1.0.2
homepage: https://github.com/nazarpunk/flutter-photoline
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter
  photoline:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

