name: photoline_example
description: Photoline plugin.
version: 1.0.2
homepage: https://github.com/nazarpunk/flutter-photoline
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_picker: ^1.1.2
  photoline:
    path: ../

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/v2/avatar/
    - assets/svg/v2/carousel/
    - assets/svg/v2/star/
    - assets/svg/v2/icon/
    - assets/svg/v2/logo/


