name: photoline_example
description: Photoline plugin.
version: 1.0.2
homepage: https://github.com/nazarpunk/flutter-photoline
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  photoline:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

