# https://dart.dev/tools/linter-rules/all
# https://dart.dev/tools#ides-and-editors
include: analysis_options_all.yaml

formatter:
  page_width: 500
  trailing_commas: preserve

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    dead_code: warning
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error

linter:
  # https://dart.dev/tools/linter-rules
  # https://dart.dev/tools/analysis

  rules:
    document_ignores: false
    avoid_field_initializers_in_const_classes: false
    avoid_implementing_value_types: false
    prefer_constructors_over_static_methods: false
    #
    prefer_mixin: false # https://dart-lang.github.io/linter/lints/prefer_mixin.html
    always_specify_types: false # https://dart-lang.github.io/linter/lints/always_specify_types.html
    #
    avoid_final_parameters: false # https://dart-lang.github.io/linter/lints/avoid_final_parameters.html
    prefer_final_parameters: false # https://dart-lang.github.io/linter/lints/prefer_final_parameters.html
    parameter_assignments: false # https://dart-lang.github.io/linter/lints/parameter_assignments.html
    #
    avoid_bool_literals_in_conditional_expressions: false # https://dart.dev/tools/linter-rules/avoid_bool_literals_in_conditional_expressions
    always_put_control_body_on_new_line: false # https://dart-lang.github.io/linter/lints/always_put_control_body_on_new_line.html
    avoid_equals_and_hash_code_on_mutable_classes: false # https://dart.dev/tools/linter-rules/avoid_equals_and_hash_code_on_mutable_classes
    empty_catches: false # https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=empty_catches#empty_catches
    specify_nonobvious_local_variable_types: false # https://dart.dev/tools/linter-rules/specify_nonobvious_local_variable_types
    strict_top_level_inference: false # https://dart.dev/tools/linter-rules/strict_top_level_inference
    omit_obvious_property_types: false # https://dart.dev/tools/linter-rules/omit_obvious_property_types
    specify_nonobvious_property_types: false # https://dart.dev/tools/linter-rules/specify_nonobvious_property_types
    unsafe_variance: false # https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unsafe_variance#unsafe_variance
    unnecessary_async: false # https://dart.dev/tools/linter-rules/unnecessary_async
    avoid_private_typedef_functions: false
    prefer_double_quotes: false
    unnecessary_final: false
    public_member_api_docs: false
    prefer_expression_function_bodies: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false
    prefer_asserts_with_message: false
    prefer_relative_imports: false
    diagnostic_describe_all_properties: false
    avoid_catches_without_on_clauses: false
    avoid_setters_without_getters: false
    always_put_required_named_parameters_first: false
    avoid_positional_boolean_parameters: false
    prefer_int_literals: false
    avoid_multiple_declarations_per_line: false
    no_runtimeType_toString: false
    unnecessary_raw_strings: false
    require_trailing_commas: false # https://dart-lang.github.io/linter/lints/require_trailing_commas.html
    # pedantic
    omit_local_variable_types: false
    # experimental
    use_build_context_synchronously: false #https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html
    use_late_for_private_fields_and_variables: false # https://dart-lang.github.io/linter/lints/use_late_for_private_fields_and_variables.html
    no_default_cases: false # https://dart-lang.github.io/linter/lints/no_default_cases.html
    # reccomended
    provide_deprecation_message: false
    # need fix
    type_annotate_public_apis: false

